// This file is autogenerated, Do not edit it by hand.
// Rebuild by running:

// node scripts/build-shader-list.js.

export const shaderList = {
  "About": {
    "LICENSE": {
      "name": "LICENSE",
      "url": "./categories/about/LICENSE",
      "extensions": [
        "md"
      ]
    },
    "Welcome": {
      "name": "Welcome",
      "url": "./categories/about/welcome",
      "extensions": [
        "md"
      ]
    }
  },
  "Shaders": {
    "Solid Color": {
      "name": "Solid Color",
      "url": "./categories/shaders/solid-color",
      "extensions": [
        "wgsl",
        "msl",
        "hlsl",
        "glsl",
        "es3.glsl"
      ]
    }
  },
  "Snippets": {
    "Linear To Srgb": {
      "name": "Linear To Srgb",
      "url": "./categories/snippets/linear-to-srgb",
      "extensions": [
        "wgsl",
        "glsl"
      ]
    }
  }
};
