// This file is autogenerated, Do not edit it by hand.
// Rebuild by running:

// node scripts/build-shader-list.js.

export const shaderList = {
  "": {
    "CONTRIBUTING": {
      "name": "CONTRIBUTING",
      "url": "./CONTRIBUTING",
      "extensions": [
        "md"
      ]
    },
    "LICENSE": {
      "name": "LICENSE",
      "url": "./LICENSE",
      "extensions": [
        "md"
      ]
    },
    "README": {
      "name": "README",
      "url": "./README",
      "extensions": [
        "md"
      ]
    }
  },
  "Basics": {
    "basic-textures": {
      "name": "Basic Textures",
      "url": "./shaders/basics/basic-textures",
      "extensions": [
        "wgsl",
        "glsl",
        "es3.glsl"
      ]
    },
    "basic-uniforms": {
      "name": "Basic Uniforms",
      "url": "./shaders/basics/basic-uniforms",
      "extensions": [
        "wgsl",
        "glsl",
        "es3.glsl"
      ]
    },
    "basic-variables": {
      "name": "Basic Variables",
      "url": "./shaders/basics/basic-variables",
      "extensions": [
        "wgsl"
      ]
    }
  },
  "Misc": {
    "linear-to-srgb": {
      "name": "Linear To Srgb",
      "url": "./shaders/misc/linear-to-srgb",
      "extensions": [
        "wgsl",
        "glsl"
      ]
    }
  },
  "Rendering": {
    "textured-geometry": {
      "name": "Textured Geometry",
      "url": "./shaders/rendering/textured-geometry",
      "extensions": [
        "wgsl",
        "hlsl",
        "glsl",
        "es3.glsl"
      ]
    }
  }
};
